let categories = [
  "Banking",
  "Financial Services",
  "Branding",
  "Construction",
  "Coworking",
  "CRM",
  "Virtual Office",
  "Cryptocurrency",
  "Ecommerce",
  "Marketplace",
  "NGO",
  "EdTech",
  "FMCG",
  "Conglomerate",
  "Foundation",
  "Gaming",
  "Sports",
  "Government Agency",
  "Health",
  "Media",
  "Entertainment",
  "Newspaper",
  "Blog",
  "Petroleum and Gas",
  "Product Design",
  "Real Estate",
  "Restaurant",
  "Software",
  "ICT",
  "Telecommunication",
  "ISP",
  "Transportation",
  "Agritech",
  "Publishing",
  "Web Host",
  "Domain Registrar",
  "Local Search",
  "Business Ratings and Reviews",
  "Online Food Delivery",
  "Event Management",
  "PropTech",
];
